default:
  tags:
    - docker
  image: reg1stry.g1tlab.1nnov8.de/r/rc-tools/xbuildimg/rcbuild-go:1.26.7

stages:
  - semvertag
  - test

# include semantic versioning autotagging CI
# Remember to a project CI var BOT_ACCESS_TOKEN containing it
# and actually there appears to be a bug, trying with temp hack:
# ref: https://gitlab.com/gitlab-org/gitlab/-/issues/259665#note_451973854
# temp hack doesn't work, but now a permanent CI bot (r-ci-bot) has been defined,
# for whom the correct personal access token should be used
include:
  - project: "r/deploy/iss"
    file: "semvertag.gitlab-ci.yml"

.go-job:
  stage: test
  variables:
    GOPROXY: "http://ryzerv.1nnov8.eu:3000,direct"
    GONOSUMDB: "g1tlab.1nnov8.de/*,rain.cloud/*" # !!! *always* set this when using the proxy !!!
    GOTOOLCHAIN: local # avoid downloading minor new go versions if the build image slightly lags
    GOMODCACHE: "${CI_PROJECT_DIR}/.gomodcache"

test-check:
  extends: .go-job
  script: |
    make check

test-unit:
  extends: .go-job
  script: |
    make test
    make test-coverage
